"""empty message

Revision ID: 149369c1fe67
Revises: ebc250fc279e
Create Date: 2020-10-22 15:41:11.832179

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '149369c1fe67'
down_revision = 'ebc250fc279e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aanwezig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornaam', sa.String(length=20), nullable=False),
    sa.Column('achternaam', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niet_aanwezig',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voornaam', sa.String(length=20), nullable=False),
    sa.Column('achternaam', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('niet_aanwezig')
    op.drop_table('aanwezig')
    # ### end Alembic commands ###
