"""empty message

Revision ID: 1bd1f8609d40
Revises: 149369c1fe67
Create Date: 2020-10-22 15:56:51.097647

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bd1f8609d40'
down_revision = '149369c1fe67'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leden', sa.Column('aanwezig', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leden', 'aanwezig')
    # ### end Alembic commands ###
