"""empty message

Revision ID: 2e794d87f42e
Revises: 1bd1f8609d40
Create Date: 2020-10-23 15:48:37.244456

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2e794d87f42e'
down_revision = '1bd1f8609d40'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leden', sa.Column('aanhef', sa.String(length=7), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leden', 'aanhef')
    # ### end Alembic commands ###
